<?php
    $templates[2] = array(
        'caption' => 'DefaultTemplate',
        'name' => 'default',
        'template' => '',
        'is_custom' => false,
        'type' => 'default',
        'source' => '',
        'active' => true
    );
?>
<?php
    $templates[1] = array(
        'caption' => 'HomeTemplate',
        'name' => 'home',
        'template' => '',
        'is_custom' => false,
        'type' => 'home',
        'source' => '',
        'active' => true
    );
?>
<?php
    $templates[7] = array(
        'caption' => 'PageTemplate',
        'name' => 'pageTemplate',
        'template' => '',
        'is_custom' => false,
        'type' => 'page',
        'source' => 'pages',
        'active' => true
    );
?>
<?php
    $templates[4] = array(
        'caption' => 'ProductOverviewTemplate',
        'name' => 'productOverview',
        'template' => '',
        'is_custom' => false,
        'type' => 'product-overview',
        'source' => 'products,categories',
        'active' => true
    );
?>
<?php
    $templates[3] = array(
        'caption' => 'ProductsTemplate',
        'name' => 'products',
        'template' => '',
        'is_custom' => false,
        'type' => 'products',
        'source' => 'categories',
        'active' => true
    );
?>
<?php
    $templates[8] = array(
        'caption' => 'ShoppingCartTemplate',
        'name' => 'shoppingCartTemplate',
        'template' => '',
        'is_custom' => false,
        'type' => 'shopping-cart',
        'source' => '',
        'active' => true
    );
?>
<?php
    $templates[9] = array(
        'caption' => 'Template404',
        'name' => 'template404',
        'template' => '',
        'is_custom' => false,
        'type' => '404',
        'source' => '',
        'active' => true
    );
?>