<div class="data-control-id-48075 bd-productsgridbar-28">
    <div class="bd-container-inner">
        <div class="data-control-id-2350 bd-layoutcontainer-27 bd-columns bd-no-margins">
    <div class="bd-container-inner">
        <div class="container-fluid">
            <div class="row 
 bd-row-flex 
 bd-row-align-middle">
                <div class="data-control-id-55013 bd-columnwrapper-8 
 col-md-6
 col-sm-6">
    <div class="bd-layoutcolumn-8 bd-column" ><div class="bd-vertical-align-wrapper"><div class="data-control-id-2352 bd-typeselector-1">
    
</div></div></div>
</div>
	
		<div class="data-control-id-2346 bd-columnwrapper-53 
 col-md-3
 col-sm-4">
    <div class="bd-layoutcolumn-53 bd-column" ><div class="bd-vertical-align-wrapper"><?php if ($_helper = Mage::registry('templateHelper')): ?>
    <?php echo $_helper->createTemplate('products-grid/sorter', 1)->setContext($this)->toHtml() ?>
<?php endif ?></div></div>
</div>
	
		<div class="data-control-id-2348 bd-columnwrapper-54 
 col-md-3
 col-sm-2">
    <div class="bd-layoutcolumn-54 bd-column" ><div class="bd-vertical-align-wrapper"><?php if ($_helper = Mage::registry('templateHelper')): ?>
    <?php echo $_helper->createTemplate('products-grid/per-page', 1)->setContext($this)->toHtml() ?>
<?php endif ?></div></div>
</div>
            </div>
        </div>
    </div>
</div>
    </div>
</div>