<?php
    $templatesPreview[2] = array(
        'url' => Mage::helper('billionthemler/url')->getPreviewUrl('designer/template/default')
    );
?>
<?php
    $templatesPreview[1] = array(
        'url' => Mage::helper('billionthemler/url')->getPreviewUrl('cms/index/index')
    );
?>
<?php
    $templatesPreview[7] = array(
        'url' => Mage::helper('billionthemler/url')->getPagePreviewUrl()
    );
?>
<?php
    $templatesPreview[4] = array(
        'url' => Mage::helper('billionthemler/url')->getProductPreviewUrl()
    );
?>
<?php
    $templatesPreview[3] = array(
        'url' => Mage::helper('billionthemler/url')->getCategoryPreviewUrl()
    );
?>
<?php
    $templatesPreview[8] = array(
        'url' => Mage::helper('billionthemler/url')->getPreviewUrl('checkout/cart/index')
    );
?>
<?php
    $templatesPreview[9] = array(
        'url' => Mage::helper('billionthemler/url')->getPreviewUrl('no/route/path')
    );
?>